### PR TITLE
Phase cam6110 new version

### PR DESCRIPTION
**Pull request by ChiaraSelmi**
Modification of the current code to have the client-server structure also for the interferometers that use WCF interface for 4Sight software in order to add the possibility to acquire burst frame using the burst acquisition function provide by 4D. This function has been implemented in the abstract interferometers and also added in all actual devices.

Tested using the Padova interferometer.

### CODE REVIEW

**Review by lbusoni — COMMENTED** [review]
Deleting plico_interferometer.client.interferometer_WCF_client.py would break interferometer_4SightFocus_client in plico_interferometer.__init__

Is this wanted? Why don't we keep the possibility of connecting to a WCF interferometer without server when the burst is not needed? Both options may co-exist: it is just a matter of proper naming and a proper documentation in __init__ where the client is constructed.

**Comment by ChiaraSelmi** [comment]
Yes deleting the file plico_interferometer.client.interferometer_WCF_client.py was intentional, but then I forgot to also delete the function interferometer_4SightFocus_client from the init.
The motivation was to keep the server-client structure the same for all devices, but actually we could also do it differently. 

Being already present and functioning in the main the possibility of connecting to a WCF interferometer without server (and also partially documented) we can decide to keep both.
 
@alfiopuglisi do you have any comments? Otherwise I proceed to re-establish the old structure.

**Comment by alfiopuglisi** [comment]
I have never used the plico interferometer code, so I don't really have an opinion on this...

**Comment by ChiaraSelmi** [comment]
News:
- I used the command git revert --no-commit <commit> to restore files and changes made for the deletion of the direct connection to the WCF. 
- Commit and test on the Padova interferometer (PhaseCam 4030)
- Updating the file readme.md

Codecov reports 4 missing lines of code for the test but in reality all tests are missing: can I work on this later on a new dedicated branch?

**Comment by ChiaraSelmi** [comment]
Code tested with the AccuFitz.
Modifications following the server's ones.

**Pull request merged**
